### ISSUE TITLE
Best way to install package?

### ISSUE THREAD

**Issue by sangwon-hyun** [seaflow-uw/popcycle#64]
Hello! I'm an avid user of your package :) What is the preferred installation method?

(I used `devtools::github_install("https://github.com/seaflow-uw/popcycle")` and selected "no updates" when asked. It still took at least 30 minutes to install the package, mainly because the many dependent R packages that were installed as part of this installation.)

**Comment by ctberthiaume** [comment]
Short answer, if you want to skip installation headaches and compilation time and are comfortable with Docker, use our Docker image. `docker pull ctberthiaume/popcycle:4.17.0`. It's based on `rocker/rstudio:4.2.1`. I usually run it with Rscript command-line scripts using a command similar to this:

```
docker run -it --rm -v $(pwd):/data ctberthiaume/popcycle:4.17.0 bash
```

And then cd to `/data` where I have my scripts and data.

You could also use the Rstudio web IDE for R console/notebook access. See https://rocker-project.org/images/versioned/rstudio.html

If you want to make changes to the Docker image, for example by modifying popcycle or installing new dependencies, it's easy enough to make those changes and then `docker commit` a new version of the image. The original image build process is captured here https://github.com/seaflow-uw/popcycle/blob/master/docker/Dockerfile

Otherwise, we have used devtools to install the pacakge, as you have also done. Unfortunately there are dependencies, I think related to flowcore, which significantly slow down the install process. Here's our script we use to do the install. https://github.com/seaflow-uw/popcycle/blob/master/setup.R. I believe it would be essentially equivalent to what you've done with some extra steps to make sure devtools and biocmanager are installed.

We've also started experimenting with using renv for dependency environment isolation and consistency. I would say that renv itself is still a work in progress and may not provide the most user-friendly experience. You can see the basic process for installing with renv in https://github.com/seaflow-uw/popcycle/blob/master/renv-first-install.R
renv is in fact what we use to build the Docker image.

**Comment by sangwon-hyun** [comment]
I'm satisfied with the installation instructions as of now.
